In [91]:
# Import numpy library
import numpy as np

## Arranging a matrix

#### This code will throw an error if the mulitplication of the values in reshape is not eqaul to the values indicated for the matrix - np.arrange

In [116]:
x = np.matrix(np.arange(12).reshape((3,4)))
x

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [153]:
Old =  np.array([[1,2,3,4,7,9], [4,5,6,7,9,10]])
Old

array([[ 1,  2,  3,  4,  7,  9],
       [ 4,  5,  6,  7,  9, 10]])

In [154]:
New = Old.reshape((3,4))
New

array([[ 1,  2,  3,  4],
       [ 7,  9,  4,  5],
       [ 6,  7,  9, 10]])

In [155]:
New = Old.reshape((3,2,2))
New

array([[[ 1,  2],
        [ 3,  4]],

       [[ 7,  9],
        [ 4,  5]],

       [[ 6,  7],
        [ 9, 10]]])

#### Converting matrix to list

In [117]:
x.tolist()

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

## Interpreting an array as a matrix

In [93]:

x = np.array([[1,2,3,4], [2,4,6,8]])
m = np.asmatrix(x)
m

matrix([[1, 2, 3, 4],
        [2, 4, 6, 8]])

In [94]:
x[0,2] = 12
x

array([[ 1,  2, 12,  4],
       [ 2,  4,  6,  8]])

In [95]:
m = np.asmatrix(x)
m

matrix([[ 1,  2, 12,  4],
        [ 2,  4,  6,  8]])

### Return string from an array or string of data

In [101]:
a = np.matrix('1 2; 3 4')
print(a)

[[1 2]
 [3 4]]


In [102]:
np.matrix([[1, 2], [3, 4]])


matrix([[1, 2],
        [3, 4]])

### switching the diagonal

In [110]:
a.getT()

matrix([[1, 3],
        [2, 4]])

## Constructing a block of a matrix

In [105]:
A = np.mat('1 1; 1 1')
B = np.mat('2 2; 2 2')
C = np.mat('3 4; 5 6')
D = np.mat('7 8; 9 0')



In [107]:
A

matrix([[1, 1],
        [1, 1]])

In [106]:
np.bmat([[A, B], [C, D]])

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

In [108]:
# or 
np.bmat('A,B; C,D')

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

In [ ]:
# or 

## Identity or unit Matrix


In [160]:
b = np.zeros((4,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [161]:
b[[0,1,2,3], [0,1,2,3]] = 1
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Using the identity library in numpy 

In [3]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

## Zero Matrix

In [4]:
np.zeros ((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Ones matrix

In [5]:
np.ones((7,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

### Diagonal Matrix

In [163]:
b = np.zeros((4,4))
b[[0,1,2,3], [0,1,2,3]] = (1,2,3,4)
b

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]])

### Scalar Matrix

In [164]:
b = np.zeros((4,4))
b[[0,1,2,3], [0,1,2,3]] = (4)
b

array([[4., 0., 0., 0.],
       [0., 4., 0., 0.],
       [0., 0., 4., 0.],
       [0., 0., 0., 4.]])

## Classwork
### Matrix manipulation with numpy library

In [6]:
output = np.ones((5,5))
output


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
inner = np.zeros((3,3))
inner
inner[1,1] = 9
inner

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [8]:
output[1:4, 1:4] = inner      #or output[1:-1, 1:-1]
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Writing the code for lower triangular Matrix

In [23]:
out = np.zeros((3,3))
out

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
out[0,0] = 9
out

array([[9., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
out [2,2] = 10
out

array([[ 9.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0., 10.]])

In [26]:
inner = np.ones((2,2))
inner

array([[1., 1.],
       [1., 1.]])

In [29]:
out [1:3,0:2] = inner
out

array([[ 9.,  0.,  0.],
       [ 1.,  1.,  0.],
       [ 1.,  1., 10.]])

## Upper  triangular matrix 
### Upper traingular matrix is the Transpose of lower triangualar matrix

In [30]:
out.T

array([[ 9.,  1.,  1.],
       [ 0.,  1.,  1.],
       [ 0.,  0., 10.]])

## Transpose of a Matrix

In [15]:
Value = np.random.randint(9, size=(2,3)) 
Value

array([[3, 8, 0],
       [8, 7, 0]])

In [16]:
# Transpose 
Value.T

array([[3, 8],
       [8, 7],
       [0, 0]])

## Square matrix 

In [17]:
Value = np.random.randint(9, size=(4,4)) 
Value

array([[1, 4, 0, 8],
       [6, 1, 4, 8],
       [7, 2, 0, 7],
       [5, 4, 3, 6]])

## Strictly lower triangular matrix
Strictly lower triangular matrix is a matrix that hass the diagonal equal to zero

In [71]:
lower = np.zeros((6,6), dtype= "int32")
lower

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [72]:
inner = np.ones((3,3), dtype= "int32")
inner

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [73]:
lower [3:6, 0:3] = inner
lower

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0]])

In [74]:
lower[1:3, :1 ] = 3
lower

array([[0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0]])

In [75]:
lower [2,1] = 10
lower

array([[ 0,  0,  0,  0,  0,  0],
       [ 3,  0,  0,  0,  0,  0],
       [ 3, 10,  0,  0,  0,  0],
       [ 1,  1,  1,  0,  0,  0],
       [ 1,  1,  1,  0,  0,  0],
       [ 1,  1,  1,  0,  0,  0]])

In [76]:
lower [5,1] = 8
lower

array([[ 0,  0,  0,  0,  0,  0],
       [ 3,  0,  0,  0,  0,  0],
       [ 3, 10,  0,  0,  0,  0],
       [ 1,  1,  1,  0,  0,  0],
       [ 1,  1,  1,  0,  0,  0],
       [ 1,  8,  1,  0,  0,  0]])

In [77]:
lower [4,0:3] = 7
lower

array([[ 0,  0,  0,  0,  0,  0],
       [ 3,  0,  0,  0,  0,  0],
       [ 3, 10,  0,  0,  0,  0],
       [ 1,  1,  1,  0,  0,  0],
       [ 7,  7,  7,  0,  0,  0],
       [ 1,  8,  1,  0,  0,  0]])

## Strictly upper triangular matrix
We take the transpose of the stricitly lower triangular matrix 

In [78]:
lower.T

array([[ 0,  3,  3,  1,  7,  1],
       [ 0,  0, 10,  1,  7,  8],
       [ 0,  0,  0,  1,  7,  1],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

## Addition of Matrix 

In [80]:
a = np.array([1,2,3,4,5])
b =  np.array([1,5,7,2,8])
print (a+b)

[ 2  7 10  6 13]


In [81]:
a + 5

array([ 6,  7,  8,  9, 10])

#### Summing all the values in a matrix

In [141]:
x = np.matrix([[1, 2], [4, 3]])
x.sum()

10

#### Suuming the values along the row

In [142]:
x.sum(axis = 1, dtype='float')

matrix([[3.],
        [7.]])

#### Summing the values along the columns

In [146]:
x.sum(axis = 0)

matrix([[5, 5]])

In [ ]:
#### 

In [149]:
out = np.zeros((2, 1), dtype = 'float')

In [152]:
x.sum(axis=0, dtype='float', out=out)


ValueError: output parameter for reduction operation add has a reduction dimension not equal to one (required when keepdims=True)

## Multiplication of Matrix

In [82]:
a =  np.ones((2,3))
print (a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [83]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

## Determinant of Matrix

In [85]:
c =  np.identity(3)
np.linalg.det(c)

1.0

In [86]:
d =  np.random.randint(9, size = (3,3))
np.linalg.det(d)

-4.999999999999998

In [90]:
np.eye(3, k=1)


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]])